<a href="https://colab.research.google.com/github/thoufiqz55/Mini_pr_Numpy/blob/main/mini_pr_and_KAG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mini Project


In [ ]:
import numpy as pd

In [ ]:
print("\n Type of data: \n\n",type(data))


 Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
new_record = [[50,9,4,1,0,0,40,0]]
new_data = np.concatenate((data,new_record),axis=0)
print(new_data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
age = new_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [ ]:
max_age = age.max()
min_age = age.min()
age_mean = age.mean()
age_std = age.std()
print(max_age)
print(min_age)
print(age_mean)
print(age_std)

90.0
17.0
38.06293706293706
13.341478176165857


In [ ]:
race = new_data[:,2]
race_0 = race[race==0]
race_1 = race[race==1]
race_2 = race[race==2]
race_3 = race[race==3]
race_4 = race[race==4]
print(race_0)
print(race_1)
print(race_2)
print(race_3)
print(race_4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [ ]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)
print(len_0)
print(len_1)
print(len_2)
print(len_3)
print(len_4)

10
27
110
6
848


In [ ]:
lenl = [len_0,len_1,len_2,len_3,len_4]
lens = np.array(lenl)
print(lens.min())
print(np.argwhere(lens==6))

6
[[3]]


In [ ]:
minority_race = 3

In [ ]:
senior_citizens = age[age>60]
print(len(senior_citizens))

61


In [ ]:
working_hour = new_data[:,6]
working_hours_sum = np.sum(working_hour[age>60])

print("Total Working hours of senior citizens:", np.sum(working_hour[age>60]))

Total Working hours of senior citizens: 1917.0


In [ ]:
senior_citizens_len = len(senior_citizens)
avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours)

31.42622950819672


In [ ]:
if avg_working_hours <=25:
    print("Govt policy is followed")
else:
    print("Govt policy is not followed")

Govt policy is not followed


In [ ]:
edu = new_data[:,1]
high = edu[edu>10]
low = edu[edu<=10]
print(high)
print(low)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [ ]:
print(len(high))
print(len(low))

327
674


In [ ]:
income = new_data[:,7]
avg_pay_high = np.mean(income[edu>10])
print(avg_pay_high)
avg_pay_low = np.mean(income[edu<=10])
print(avg_pay_low)

0.42813455657492355
0.13649851632047477


In [ ]:
data = np.genfromtxt("KAG_Conversion_Data.csv", delimiter=",",skip_header=1)
print("\nData: \n\n",data)


Data: 

 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [ ]:
import numpy as np
data = np.genfromtxt('makeSenseOfCensus.csv', delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


#KAG conversion


In [ ]:
print('\nType of data: \n\n',type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
un_ad = data[:,0]
print(un_ad)
print(len(un_ad))

[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]
1143


In [ ]:
xyz_cam = data[:,1]
print(xyz_cam)
print(len(xyz_cam))

[ 916.  916.  916. ... 1178. 1178. 1178.]
1143


In [ ]:
print(np.unique(xyz_cam))

[ 916.  936. 1178.]


In [ ]:
age_group = data[:,3]
print(np.unique(age_group))
print(age_group)


[nan nan nan ... nan nan nan]
[nan nan nan ... nan nan nan]


In [ ]:
spnt = data[:,8]
print(spnt)
print(spnt.mean())
print(spnt.min())
print(spnt.max())


[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]
51.36065613141295
0.0
639.9499981


In [ ]:
clk = data[:,9]
print(clk.max())

60.0


In [ ]:
print(un_ad[clk==60])

[1121100.]


In [ ]:
print(un_ad[clk==60])

[1121100.]


In [ ]:
ap_conv = data[:,10]
print(ap_conv[clk==60])

[17.]


In [ ]:
print(ap_conv.max())

21.0


In [ ]:
print(un_ad[ap_conv==21])

[1121104.]


In [ ]:
print(np.argwhere(un_ad==1121104))

[[528]]


In [ ]:
print(data[528])

[1.12110400e+06 1.17800000e+03 1.44533000e+05            nan
            nan 1.60000000e+01 2.08066600e+06 2.02000000e+02
 3.60150001e+02 4.00000000e+01 2.10000000e+01]
